### ISSUE TITLE
Decide which language to use for this

### ISSUE THREAD

**Issue by artheus** [artheus/KiutD#1]
Currently considering alternatives:

* GoLang
* Java
* Python
* Javascript (NodeJS)

**Comment by artheus** [comment]
My language of choice will be GoLang. I choose this language as it is x-platform, easy to use, modular and pretty low level. It is also possible to use this for building for multiple architectures and also for jvm.

**Comment by xferra** [comment]
If you did not start with the implementation I may offer you to join the similar project. Are you still interested in dep/pkg management?

**Comment by artheus** [comment]
@xferra Alright! Sounds great! I have done some small things here, but not much. I am still very interested. Which project is that?
